language: ruby
sudo: false
cache:
  - bundler
  - apt

services:
  - memcached

addons:
  apt:
    packages:
      - lighttpd
      - libfcgi-dev

before_install:
  - gem env version | grep '^\(2\|1.\(8\|9\|[0-9][0-9]\)\)' || gem update --system

script: bundle exec rake ci

rvm:
  - 2.4.1

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
